title: Cadastro de Configurações

input::confName:
  name: Nome da configuração:
  message: Entre com o nome da configuração:

input::appName:
  name: Nome da aplicação:
  message: Entre com o nome da aplicação ligada a esta credencial:
  validator: $F$appsNameValidator

minput::values:
  name: Valores:
  message: Entre com o valor:
  interactions: $F$appsEnvironmentsLister

# MISC CONFIGS
yes_no: '[S/N]'
yes: S
no: N
invalid_value: Valor inválido
